# Generated by Django 5.2.5 on 2025-09-22 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='სახელი')),
                ('last_name', models.CharField(max_length=100, verbose_name='გვარი')),
                ('email', models.EmailField(max_length=254, verbose_name='მეილი')),
                ('birth_date', models.DateField(null=True, verbose_name='დაბადების თარიღი')),
            ],
            options={
                'verbose_name': 'Author',
                'verbose_name_plural': 'Authors',
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='სათაური')),
                ('text', models.TextField(verbose_name='ტექსი')),
                ('active', models.BooleanField(default=True, verbose_name='აქტიურია')),
                ('create_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='შექმნის თარიღი')),
                ('update_date', models.DateTimeField(auto_now=True, null=True, verbose_name='განახლების თარიღი')),
                ('website', models.URLField(null=True, verbose_name='ვებ მისამართი')),
                ('document', models.FileField(blank=True, null=True, upload_to='blog_document/')),
                ('deleted', models.BooleanField(default=False, verbose_name='წაშლილია')),
                ('category', models.IntegerField(choices=[(1, 'Political'), (2, 'Education'), (3, 'Entertainment')], null=True, verbose_name='Category')),
                ('authors', models.ManyToManyField(related_name='blog_posts', to='blog.author', verbose_name='ავტორები')),
            ],
            options={
                'verbose_name': 'Blog Post',
                'verbose_name_plural': 'Blog Posts',
                'ordering': ['title'],
                'unique_together': {('title', 'text')},
            },
        ),
        migrations.CreateModel(
            name='BannerImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='banner_image/')),
                ('blog_post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='banner_image', to='blog.blogpost')),
            ],
            options={
                'verbose_name': 'Banner Image',
                'verbose_name_plural': 'Banner Images',
            },
        ),
        migrations.CreateModel(
            name='BlogPostImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='blog_image/')),
                ('blog_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='blog.blogpost')),
            ],
            options={
                'verbose_name': 'Blog Post Image',
                'verbose_name_plural': 'Blog Post Images',
            },
        ),
    ]
